### ISSUE TITLE
Test fail for MacOS-latest with python3.8

### ISSUE THREAD

**Issue by m-rothe** [internet-sicherheit/pive#6]
Some test fail with configuration macos-latest and python 3.8

This should currently be supported.

**Comment by m-rothe** [comment]
Failed test are those that involve threading with "multiprocessing"-library. On python3.8 for MacOS  Mojave default behaviour was changed from "fork" to "spawn", which also is the only available method on Windows too.
This library was chosen over pythons internal threading mechanism to terminate the function calls in case something is broken.  
Spawn requires that called target and its arguments are pickleable, but the unittest objects seem to not be pickleable.

The test cases in question have been rewritten to omit references to the calling unittest object.  
Additionally the timeout time has been increased so the test cases run on machines with slower IO.

**Comment by kiview** [comment]
I wonder if the multiprocessing makes sense in your architecture.
Don't you run pive on a server that does request based threading/processes? Very rarely it is sensible to do an additional fan out later.

**Comment by m-rothe** [comment]
The multiprocessing calls are in the test cases only with test cases where a locking might be expensive or not fix itself in case of error. As python threads cant easily be killed, this enables to continue in case of error.
